import json

manifest_en = "g:/Work/git/Bloret-Launcher/lang/en-US.json"

translations = {
    "联机服务 Powered by EasyTier. 对方也需要安装 Bloret Launcher 或 EasyTier 才能加入。": "Multiplayer service powered by EasyTier. The other player must install Bloret Launcher or EasyTier to join.",
    "屏幕截图": "Screen Capture",
    "下载并安装原生 Minecraft 核心": "Download and install vanilla Minecraft core",
    "让络可帮你挑选合适的 Mod": "Let Bloriko help you pick the right Mod",
    "运行 Minecraft 所需的 Java 环境": "Java environment required to run Minecraft",
    "通过 Bloret PassPort 管理你的账户": "Manage your account via Bloret PassPort",
    "选择 Minecraft 版本": "Select Minecraft Version",
    "打开插件目录": "Open Plugin Directory",
    "Conveniently manage your Minecraft, conveniently play Bloret.\\n便捷地管理你的 Minecraft，便捷地游玩 Bloret。": "Conveniently manage your Minecraft, conveniently play Bloret.\\n便捷地管理你的 Minecraft，便捷地游玩 Bloret。",
    "管理已安装插件，查看信息或卸载": "Manage installed plugins, view info or uninstall",
    "选择安装版本": "Select Version to Install",
    "？": "?",
    "选择版本:": "Select version:",
    "告诉 Bloriko 你的需求...": "Tell Bloriko what you need...",
    "络可正在思考建议...": "Bloriko is thinking of a suggestion...",
    "刷新": "Refresh",
    "作为加入者": "Join",
    "确定": "Confirm",
    "关于 Minecraft 的任何问题，可以问络可哦 ~": "Ask Bloriko any questions about Minecraft ~",
    "Java 运行时环境": "Java Runtime Environment",
    "网站管理": "Manage on Website",
    "Minecraft 账户": "Minecraft Account",
    "卸载成功": "Uninstalled Successfully",
    "卸载插件": "Uninstall Plugin",
    "版本类别:": "Version Category:",
    "作为房主": "Host",
    "v未知": "vUnknown",
    "让络可好好想想...": "Let Bloriko think about it...",
    "搜索": "Search",
    "关闭": "Close",
    "Minecraft 官方版本": "Official Minecraft Version",
    "Bloret Launcher": "Bloret Launcher",
    "安装 Fabric 加载器以使用 modern Mod": "Install Fabric loader to use modern Mods",
    "卸载": "Uninstall",
    "Bloret PassPort": "Bloret PassPort",
    "深度思考": "Deep Think",
    "无档案": "No profile",
    "小工具": "Tools",
    "Minecraft 数据查询": "Minecraft Data Query",
    "Bloret Launcher Screen Cut": "Bloret Launcher Screen Cut",
    "查看": "View",
    "信息": "Info",
    "披风的查询的结果": "Cape Query Result",
    "暂无账户，请从云端同步": "No accounts yet, please sync from cloud",
    "连接节点": "Connect Node",
    "访客": "Guest",
    "查看您计算机的 IPV6 配置": "View your computer's IPv6 configuration",
    "Bloriko 的建议": "Bloriko's Suggestion",
    "外部程序/整合包": "External App / Modpack",
    "未命名插件": "Unnamed Plugin",
    "获取玩家的皮肤和披风": "Get player's skin and cape",
    "暂无插件": "No Plugins",
    "使用 Bloret 通行证，可享受几乎所有的 Bloret 服务。": "Use Bloret PassPort to enjoy almost all Bloret services.",
    "复制": "Copy",
    "请选择要安装此 Mod 的 Fabric 版本:": "Please select the Fabric version to install this Mod:",
    "前往": "Go",
    "使用此账户": "Use this account",
    "截图": "Capture",
    "网络": "Network",
    "EasyTier 组网": "EasyTier Networking",
    "添加您的自定义启动项或整合包文件": "Add your custom launcher item or modpack file",
    "添加自定义项目": "Add Custom Item",
    "日志已成功清空": "Logs successfully cleared",
    "玩家UUID": "Player UUID",
    "玩家名称（正版）": "Player Name (Original)",
    "IPV6": "IPV6",
    "请选择要推荐模组的 Minecraft 版本（仅支持 Fabric）：": "Please select the Minecraft version to recommend mods (Fabric only):",
    "确认卸载插件：": "Confirm plugin uninstall:",
    "查询玩家名字": "Query Player Name",
    "退出登录": "Logout",
    "查询的结果将显示在这里": "Query result will show here",
    "轻松登录你的 Minecraft Account，便捷地进行操作。": "Easily log into your Minecraft Account and perform operations smoothly.",
    "卸载后会删除插件文件，并移除相关启动项。": "Uninstalling will delete the plugin file and remove related launch items.",
    "Mods": "Mods",
    "查询": "Query",
    "已成功从云端同步账户": "Successfully synced account from cloud",
    "作者: ": "Author: ",
    "Bloriko 依靠 AI。Bloriko 也可能犯错，请核实重要信息。": "Bloriko relies on AI. Bloriko may make mistakes; please verify important info.",
    "皮肤的查询的结果": "Skin Query Result",
    "发送": "Send",
    "络可推荐时间段": "Bloriko's Recommended Time",
    "正在加载版本...": "Loading versions...",
    "Fabric Loader": "Fabric Loader",
    "正在使用": "Currently In Use",
    "查询中...": "Querying...",
    "成功": "Success",
    "插件": "Plugins",
    "同步时出错: ": "Error while syncing: ",
    "在 Modrinth 上搜索...": "Search on Modrinth...",
    "登录": "Login",
    "无需一个一个找 Mod，让 Bloriko 帮你找齐。": "No need to find Mods one by one, let Bloriko find them for you.",
    "打开文件夹": "Open Folder",
    "插件已卸载": "Plugin Uninstalled",
    "便捷地截取屏幕画面，包括 Minecraft 窗口": "Conveniently capture screen content, including Minecraft window",
    "💡 提示：复制上方推荐中的模组名称，在搜索框搜索即可一键安装。": "💡 Tip: Copy the Mod name from the recommendation above and search in the box to one-click install.",
    "卸载失败": "Uninstall Failed",
    "云端同步": "Cloud Sync",
    "作者: 未知": "Author: Unknown",
    "Bloret Server 数据信息提供自 百络谷查服网": "Bloret Server data provided by Bloret Server Query",
    "启动服务器": "Start Server",
    "切换核心": "Switch Core",
    "查询玩家UUID": "Query Player UUID",
    "下载并安装": "Download & Install",
    "已安装的插件": "Installed Plugins",
    "暂无插件描述": "No description for plugin",
    "其他版本...": "Other versions...",
    "连接到对方": "Connect to Peer",
    "设置快捷键": "Set Shortcut",
    "请输入您的 Minecraft 端口": "Please enter your Minecraft port"
}

with open(manifest_en, 'r', encoding='utf-8') as f:
    data = json.load(f)

for k, v in data["texts"].items():
    if k in translations:
        data["texts"][k] = translations[k]

with open(manifest_en, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=4, ensure_ascii=False)

print("Updated translations in en-US.json")
