blank_issues_enabled: true
contact_links:
  - name: 讨论区
    url: https://github.com/BloretCrew/Bloret-Launcher/discussions
    about: 不确定的问题或建议，可以在这里进行讨论
  - name: QQ 群
    url: https://qm.qq.com/q/Q07CSpcP6i
    about: 欢迎加入 百洛谷 QQ群
