# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ScreenCut.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(240, 81)
        self.CardWidget = CardWidget(Form)
        self.CardWidget.setGeometry(QtCore.QRect(9, 9, 223, 62))
        self.CardWidget.setObjectName("CardWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.CardWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BodyLabel_2 = BodyLabel(self.CardWidget)
        self.BodyLabel_2.setMaximumSize(QtCore.QSize(25, 25))
        self.BodyLabel_2.setText("")
        self.BodyLabel_2.setPixmap(QtGui.QPixmap("ui\\icon/home.png"))
        self.BodyLabel_2.setScaledContents(True)
        self.BodyLabel_2.setWordWrap(False)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.horizontalLayout.addWidget(self.BodyLabel_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.StrongBodyLabel = StrongBodyLabel(self.CardWidget)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.verticalLayout.addWidget(self.StrongBodyLabel)
        self.CaptionLabel_6 = CaptionLabel(self.CardWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CaptionLabel_6.sizePolicy().hasHeightForWidth())
        self.CaptionLabel_6.setSizePolicy(sizePolicy)
        self.CaptionLabel_6.setWordWrap(True)
        self.CaptionLabel_6.setProperty("lightColor", QtGui.QColor(0, 0, 0, 150))
        self.CaptionLabel_6.setProperty("darkColor", QtGui.QColor(255, 255, 255, 200))
        self.CaptionLabel_6.setObjectName("CaptionLabel_6")
        self.verticalLayout.addWidget(self.CaptionLabel_6)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.StrongBodyLabel.setText(_translate("Form", "Bloret Launcher Screen Cut"))
        self.CaptionLabel_6.setText(_translate("Form", "单击窗口或框选矩形区域以截图"))
from qfluentwidgets import BodyLabel, CaptionLabel, CardWidget, StrongBodyLabel
