name: 将 Python 打包为 EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v2

    - name: 设置 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: 安装依赖
      run: |
        pip install -r requirements.txt
        pip install loguru
        pip install PyQt-Fluent-Widgets -i https://pypi.org/simple/
        pip install pyinstaller
        pip install pillow

    - name: 使用 PyInstaller 打包
      run: pyinstaller --onefile --noconsole --icon=icons/bloret.png --name=Bloret-Launcher main.py

    - name: 创建包含其他文件夹的目录
      run: |
        mkdir -p output
        cp dist/Bloret-Launcher.exe output/
        cp -r cmcl/ output/
        cp -r icons/ output/
        cp -r log/ output/
        cp -r ui/ output/
        cp cmcl.exe output/
        cp cmcl.json output/
        cp config.ini output/

    - name: 创建压缩包
      run: Compress-Archive -Path output/* -DestinationPath output/Bloret-Launcher-Windows.zip

    - name: 上传构建产物
      uses: actions/upload-artifact@v3
      with:
        name: Bloret-Launcher
        path: output/Bloret-Launcher.exe

    - name: 上传安装包
      uses: actions/upload-artifact@v3
      with:
        name: Bloret-Launcher-Windows
        path: output/Bloret-Launcher-Windows.zip