name: 将 Python 打包为 EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v2

    - name: 设置 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: 安装依赖
      run: |
        pip install -r requirements.txt

    - name: 安装 PyQt-Fluent-Widgets
      run: pip install PyQt-Fluent-Widgets -i https://pypi.org/simple/

    - name: 安装 PyInstaller
      run: pip install pyinstaller

    - name: 使用 PyInstaller 打包
      run: pyinstaller --onefile main.py

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: Bloret-Launcher
        path: dist/
