name: 将 Python 打包为 EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v2

    - name: 设置 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: 安装依赖
      run: |
        pip install -r requirements.txt

    - name: 安装 PyQt-Fluent-Widgets
      run: pip install PyQt-Fluent-Widgets -i https://pypi.org/simple/

    - name: 安装 PyInstaller 和 Pillow
      run: |
        pip install pyinstaller
        pip install pillow

    - name: 使用 PyInstaller 打包
      run: pyinstaller --onefile --noconsole --icon=icons/bloret.png --name=Bloret-Launcher main.py

    - name: 创建包含其他文件夹的目录
      run: |
        mkdir -p output
        cp dist/Bloret-Launcher.exe output/
        cp -r cmcl/ output/
        cp -r icons/ output/
        cp -r ui/ output/
        cp config.ini output/

    - name: 创建 zip 包含构建产物
      run: |
        cd output
        powershell -command "Compress-Archive -Path Bloret-Launcher.exe, cmcl, icons, ui, config.ini -DestinationPath Bloret-Launcher.zip"

    - name: 上传构建产物 Bloret-Launcher.zip
      uses: actions/upload-artifact@v3
      with:
        name: Bloret-Launcher
        path: output/Bloret-Launcher.zip

    - name: 下载构建产物
      uses: actions/download-artifact@v3
      with:
        name: Bloret-Launcher
        path: output/

    - name: 制作安装器
      run: |
        InnoSetupCompiler output/Bloret-Launcher.zip output/Bloret-Launcher-Installer.exe

    - name: 上传安装包
      uses: actions/upload-artifact@v3
      with:
        name: Bloret-Launcher-Installer
        path: output/Bloret-Launcher-Installer.exe
