name: 将 Python 打包为 EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v2

    - name: 设置 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: 安装依赖
      run: |
        pip install -r requirements.txt

    - name: 安装 PyQt-Fluent-Widgets
      run: pip install PyQt-Fluent-Widgets -i https://pypi.org/simple/

    - name: 安装 PyInstaller 和 Pillow
      run: |
        pip install pyinstaller
        pip install pillow

    - name: 使用 PyInstaller 打包
      run: pyinstaller --onefile --noconsole --icon=icons/bloret.png --name=Bloret-Launcher main.py

    - name: 创建 zip 包含其他文件夹
      run: |
        mkdir -p output
        cp dist/Bloret-Launcher.exe output/
        cp -r cmcl/ output/
        cp -r icons/ output/
        cp -r ui/ output/
        powershell Compress-Archive -Path output/* -DestinationPath Bloret-Launcher.zip

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: Bloret-Launcher
        path: Bloret-Launcher.zip
