name: 发布正式版

on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 发布正式版
        run: |
          # 从GitHub事件中提取版本信息
          VERSION=$(echo ${{ github.event.release.tag_name }})
          VERSION_NAME=$(echo ${{ github.event.release.name }})
          DESCRIPTION=$(echo ${{ github.event.release.body }})
          
          # 调用API发布正式版
          curl -X POST http://pcfs.eno.ink:3001/api/newversion/github \
            -H "Content-Type: application/json" \
            -d "{\"key\":\"${{ secrets.BLORET_LAUNCHER_WEBSITE }}\",\"beta\":false,\"version\":\"$VERSION\",\"versionName\":\"$VERSION_NAME\",\"description\":\"$DESCRIPTION\"}"